In [9]:
import numpy as np
import pandas as pd

In [5]:
df=pd.read_csv('netflix_titles.csv')
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [6]:
df.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1357,s1358,Movie,Rocks,Sarah Gavron,"Bukky Bakray, Kosar Ali, D'angelou Osei Kissie...",United Kingdom,"February 1, 2021",2019,TV-MA,93 min,Dramas,"Following her mother's abrupt departure, a dyn..."
8575,s8576,TV Show,This Is My Love,NaN,"Jin-mo Joo, Sa-rang Kim, Junior, Ja-in Lee, Su...",South Korea,"May 22, 2017",2015,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",A renowned actor who is still pining over the ...
1027,s1028,Movie,Crimson Peak,Guillermo del Toro,"Mia Wasikowska, Jessica Chastain, Tom Hiddlest...","Canada, United States, Mexico","April 16, 2021",2015,R,119 min,"Horror Movies, Romantic Movies, Sci-Fi & Fantasy",After marrying a mysterious British aristocrat...
4788,s4789,Movie,Katt Williams: Kattpacalypse,Marcus Raboy,Katt Williams,United States,"July 3, 2018",2012,TV-MA,61 min,Stand-Up Comedy,Urban comic Katt Williams ushers in Kattpacaly...
4217,s4218,Movie,Monty Python and the Holy Grail,"Terry Gilliam, Terry Jones","Graham Chapman, John Cleese, Eric Idle, Terry ...",United Kingdom,"January 2, 2019",1975,PG,92 min,"Action & Adventure, Classic Movies, Comedies",The Monty Python comedy clan skewers King Arth...

In [7]:
df.sample() # if no number is mentioned within bracket then displays only one row

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
2389,s2390,Movie,Asura Guru,A. Raajdheep,"Vikram Prabhu, Subbaraju, Mahima Nambiar, Yogi...",India,"June 13, 2020",2020,TV-14,117 min,"Dramas, International Movies","For a tech-savvy thief, elaborate robberies an..."

In [11]:
df.drop(["show_id","description"],axis=1,inplace=True)

In [12]:
df.sample(5)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
3187,TV Show,Nightflyers,NaN,"Eoin Macken, David Ajala, Jodie Turner-Smith, ...",United States,"December 2, 2019",2018,TV-MA,1 Season,"TV Horror, TV Mysteries, TV Sci-Fi & Fantasy"
398,Movie,Kingdom: Ashin of the North,Kim Seong-hun,"Gianna Jun, Park Byung-eun, Kim Si-a, Kim Roi-...",NaN,"July 23, 2021",2021,TV-MA,94 min,"Horror Movies, International Movies, Thrillers"
8357,TV Show,The Inbetweeners,NaN,"Simon Bird, James Buckley, Blake Harrison, Joe...",United Kingdom,"January 1, 2018",2010,TV-MA,3 Seasons,"British TV Shows, TV Comedies"
6124,Movie,Alpha and Omega 2: A Howl-iday Adventure,Richard Rich,"Ben Diskin, Kate Higgins, Blackie Rose, Lindsa...",United States,"October 1, 2019",2013,TV-G,45 min,Children & Family Movies
6657,Movie,Earth to Echo,Dave Green,"Teo Halm, Astro, Reese Hartwig, Ella Wahlested...",United States,"October 1, 2019",2014,PG,91 min,"Children & Family Movies, Sci-Fi & Fantasy"

In [13]:
df.shape

(8807, 10)

In [14]:
df.size

88070

In [15]:
df.index

RangeIndex(start=0, stop=8807, step=1)

In [16]:
df.columns

Index(['type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in'],
      dtype='object')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   type          8807 non-null   object
 1   title         8807 non-null   object
 2   director      6173 non-null   object
 3   cast          7982 non-null   object
 4   country       7976 non-null   object
 5   date_added    8797 non-null   object
 6   release_year  8807 non-null   int64
 7   rating        8803 non-null   object
 8   duration      8804 non-null   object
 9   listed_in     8807 non-null   object
dtypes: int64(1), object(9)
memory usage: 688.2+ KB

In [19]:
df.isna().sum()

type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
dtype: int64

In [21]:
df["country"].value_counts().head(3)

country
United States     2818
India              972
United Kingdom     419
Name: count, dtype: int64

In [25]:
mode_country=df["country"].mode()[0]

In [26]:
mode_country

'United States'

In [28]:
df["country"]=df["country"].fillna(mode_country)

In [29]:
df["country"].isna().sum()

np.int64(0)

In [30]:
df["date_added"].value_counts().head(3)

date_added
January 1, 2020     109
November 1, 2019     89
March 1, 2018        75
Name: count, dtype: int64

In [31]:
mode_date=df["date_added"].mode()[0]

In [32]:
mode_date

'January 1, 2020'

In [33]:
df["date_added"]=df["date_added"].fillna(mode_date)

In [34]:
df["date_added"].isna().sum()

np.int64(0)

In [42]:
mode_rating=df["rating"].mode()[0]

In [43]:
mode_rating

'TV-MA'

In [46]:
df["rating"]=df["rating"].fillna(mode_rating)

In [47]:
df["rating"].isna().sum()

np.int64(0)

In [48]:
mode_duration=df["duration"].mode()[0]

In [50]:
mode_duration

'1 Season'

In [51]:
df["duration"]=df["duration"].fillna(mode_duration)

In [52]:
df["duration"].isna().sum()

np.int64(0)

In [53]:
df["director"]=df["director"].fillna("Not Mentioned")

In [54]:
df["director"].isna().sum()

np.int64(0)

In [55]:
df["cast"]=df["cast"].fillna("Not Mentioned")

In [56]:
df["cast"].isna().sum()

np.int64(0)

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   type          8807 non-null   object
 1   title         8807 non-null   object
 2   director      8807 non-null   object
 3   cast          8807 non-null   object
 4   country       8807 non-null   object
 5   date_added    8807 non-null   object
 6   release_year  8807 non-null   int64
 7   rating        8807 non-null   object
 8   duration      8807 non-null   object
 9   listed_in     8807 non-null   object
dtypes: int64(1), object(9)
memory usage: 688.2+ KB

In [58]:
df["rating"].unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', '74 min', '84 min', '66 min', 'NR',
       'TV-Y7-FV', 'UR'], dtype=object)

In [59]:
df= df[~df["rating"].str.contains("min")]

In [60]:
df["date_added"].unique()

array(['September 25, 2021', 'September 24, 2021', 'September 23, 2021',
       ..., 'December 6, 2018', 'March 9, 2016', 'January 11, 2020'],
      dtype=object)

In [61]:
df["date_added"]=df["date_added"].str.replace(",","")

C:\Users\rohit\AppData\Local\Temp\ipykernel_43768\2649166716.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date_added"]=df["date_added"].str.replace(",","")

In [62]:
df["date_added"].unique()

array(['September 25 2021', 'September 24 2021', 'September 23 2021', ...,
       'December 6 2018', 'March 9 2016', 'January 11 2020'], dtype=object)

In [63]:
df["date_added"] = pd.to_datetime(df["date_added"], format="mixed")

C:\Users\rohit\AppData\Local\Temp\ipykernel_43768\498004367.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date_added"] = pd.to_datetime(df["date_added"], format="mixed")

In [64]:
df["date_added"].unique()

<DatetimeArray>
['2021-09-25 00:00:00', '2021-09-24 00:00:00', '2021-09-23 00:00:00',
 '2021-09-22 00:00:00', '2021-09-21 00:00:00', '2021-09-20 00:00:00',
 '2021-09-19 00:00:00', '2021-09-17 00:00:00', '2021-09-16 00:00:00',
 '2021-09-15 00:00:00',
 ...
 '2018-09-27 00:00:00', '2017-03-23 00:00:00', '2016-12-25 00:00:00',
 '2016-11-30 00:00:00', '2017-10-23 00:00:00', '2017-11-04 00:00:00',
 '2015-08-05 00:00:00', '2018-12-06 00:00:00', '2016-03-09 00:00:00',
 '2020-01-11 00:00:00']
Length: 1714, dtype: datetime64[ns]

In [65]:
df["year"]=df["date_added"].dt.year

C:\Users\rohit\AppData\Local\Temp\ipykernel_43768\1025263937.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["year"]=df["date_added"].dt.year

In [66]:
df["month"]=df["date_added"].dt.month

C:\Users\rohit\AppData\Local\Temp\ipykernel_43768\4265263075.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["month"]=df["date_added"].dt.month

In [67]:
df["day"]=df["date_added"].dt.day

C:\Users\rohit\AppData\Local\Temp\ipykernel_43768\292946900.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["day"]=df["date_added"].dt.day

In [ ]:
df.sample